services:
  - type: web
    name: netflix-kingdom-bot
    env: python
    region: oregon
    plan: free
    rootDir: artifacts/bot
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 6000
